// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a.Data;

#nullable disable

namespace a.Migrations
{
    [DbContext(typeof(AreaC_Context))]
    [Migration("20251115121656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("a.Models.AR_Categories", b =>
                {
                    b.Property<long>("AR_ReserveNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AR_ReserveNum"));

                    b.Property<string>("AR_ActivityTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Approval1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Approval2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Approval3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Approval4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Approval5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("AR_DateNeeded")
                        .HasColumnType("date");

                    b.Property<int>("AR_DateSet")
                        .HasColumnType("int");

                    b.Property<string>("AR_EquipF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_NameOrg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_NatureAct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Participants")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_PurposeObj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_SourceFund")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Speaker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("AR_TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("AR_TimeTo")
                        .HasColumnType("time");

                    b.Property<string>("AR_Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AR_ReserveNum");

                    b.ToTable("AR_DB");
                });

            modelBuilder.Entity("a.Models.GP_Categories", b =>
                {
                    b.Property<long>("GP_Num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GP_Num"));

                    b.Property<string>("GP_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_App4sch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_Approval1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_Approval2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_Approval3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("GP_Classification")
                        .HasColumnType("date");

                    b.Property<string>("GP_Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("GP_Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("GP_DateExpiration")
                        .HasColumnType("date");

                    b.Property<string>("GP_Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("GP_LoadnRegis")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("GP_Marker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_Vehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GP_Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GP_Num");

                    b.ToTable("GP_DB");
                });

            modelBuilder.Entity("a.Models.L_Categories", b =>
                {
                    b.Property<long>("L_Num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("L_Num"));

                    b.Property<string>("L_Approval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("L_ContactNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("L_LoadnRegis")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("L_Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("L_StuID")
                        .HasColumnType("bigint");

                    b.Property<string>("L_StuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("L_Num");

                    b.ToTable("L_DB");
                });
#pragma warning restore 612, 618
        }
    }
}
